# Generated by Django 5.1.4 on 2024-12-31 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorian', '0001_initial'),
        ('Medecin', '0003_notification'),
        ('Radiologue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanLabRad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan_lab_rad', to='Medecin.bilan')),
                ('laboratorian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratorian.laboratorian')),
                ('radiologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Radiologue.radiologue')),
            ],
        ),
    ]
