# Generated by Django 5.1.4 on 2024-12-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Biologique', 'Biologique'), ('Radiologique', 'Radiologique')], max_length=20)),
                ('date_bilan', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre', models.CharField(max_length=100)),
                ('valeurs', models.JSONField(default=list)),
                ('unite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('administration_medicaments', models.TextField()),
                ('soins', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('medicaments', models.ManyToManyField(to='Medecin.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(auto_now_add=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('bilans', models.ManyToManyField(related_name='consultations', to='Medecin.bilan')),
                ('medecin_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medecin.medecin')),
                ('ordonnances', models.ManyToManyField(related_name='consultations', to='Medecin.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='bilan',
            name='resultat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Medecin.resultatbiologique'),
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.IntegerField(unique=True)),
                ('code_QR', models.ImageField(upload_to='qr_codes/')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('telephone_urgence', models.IntegerField()),
                ('mutuelle', models.CharField(max_length=100)),
                ('poids', models.FloatField()),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('consultations', models.ManyToManyField(related_name='dpis', to='Medecin.consultation')),
                ('medecin_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medecin.medecin')),
                ('soins', models.ManyToManyField(related_name='dpis', to='Medecin.soin')),
            ],
        ),
    ]
