# Generated by Django 5.1.4 on 2024-12-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medecin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('medecin', 'Medecin'), ('infirmier', 'Infirmier'), ('patient', 'Patient'), ('radiologue', 'Radiologue'), ('laboratorian', 'Laboratorian')], default='patient', max_length=15),
        ),
    ]
