# Generated by Django 5.1.4 on 2025-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medecin', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('medecin', 'Medecin'), ('infirmier', 'Infirmier'), ('patient', 'Patient'), ('radiologue', 'Radiologue'), ('laboratorian', 'Laboratorian'), ('admin', 'Admin')], default='patient', max_length=15),
        ),
    ]
