# Generated by Django 5.1.4 on 2024-12-27 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medecin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('medical_insurance_provider', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutuelle', models.CharField(max_length=100)),
                ('poids', models.FloatField()),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('consultations', models.ManyToManyField(related_name='dpis', to='Medecin.consultation')),
                ('medecin_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medecin.medecin')),
                ('soins', models.ManyToManyField(related_name='dpis', to='Medecin.soin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
