# Generated by Django 5.1.4 on 2024-12-24 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medecin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('medical_insurance_provider', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.IntegerField(unique=True)),
                ('code_QR', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('telephone_urgence', models.IntegerField()),
                ('mutuelle', models.CharField(max_length=100)),
                ('poids', models.FloatField()),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('consultations', models.ManyToManyField(related_name='dpis', to='Medecin.consultation')),
                ('medecin_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soins', models.ManyToManyField(related_name='dpis', to='Medecin.soin')),
            ],
        ),
    ]
